# -*- coding: utf-8 -*-
"""
Firmas para fingerprinting de tecnologías web (estilo Wappalyzer/BuiltWith).

Cada firma puede tener evidencias de varios tipos:
  - html:              regex aplicado sobre el HTML completo de las páginas.
  - scripts:           regex aplicado sobre las URL de <script src=...> e <img>/<link> externos.
  - meta_generador:    regex aplicado sobre <meta name="generator" content="...">.
  - cabeceras:         lista de tuplas (nombre_cabecera_minusculas, regex sobre el valor).
  - cabeceras_cualquiera: regex aplicado sobre "nombre: valor" de TODAS las cabeceras.
  - cookies:           regex aplicado sobre los nombres de cookies observadas.

Las categorías corresponden exactamente a las solicitadas para el reporte.
"""

CATEGORIAS = [
    "CMS",
    "Ecommerce",
    "Analytics",
    "Advertising",
    "Payments",
    "Chat y soporte",
    "Marketing",
    "Reviews",
    "Consent",
    "Experimentation",
    "Search",
    "Scheduling",
    "Frameworks",
    "CDN y hosting",
    "Server",
    "Seguridad y monitoreo",
    "Media y mapas",
    "Otros",
]

FIRMAS = [
    # ------------------------------------------------------------------ CMS
    {"nombre": "WordPress", "categoria": "CMS",
     "meta_generador": [r"wordpress"],
     "html": [r"wp-content/", r"wp-includes/"],
     "cookies": [r"^wp-settings", r"^wordpress_"]},
    {"nombre": "WooCommerce (plugin)", "categoria": "CMS",
     "html": [r"woocommerce\.min\.js", r"class=\"[^\"]*woocommerce"]},
    {"nombre": "Drupal", "categoria": "CMS",
     "meta_generador": [r"drupal"],
     "html": [r"/sites/default/", r"drupalSettings"],
     "cabeceras": [("x-generator", r"drupal"), ("x-drupal-cache", r".")],
     "cookies": [r"^SESS[a-f0-9]{32}"]},
    {"nombre": "Joomla", "categoria": "CMS",
     "meta_generador": [r"joomla"],
     "html": [r"/media/system/js/", r"/templates/[^\"']+/css/template\.css"]},
    {"nombre": "Ghost", "categoria": "CMS",
     "meta_generador": [r"ghost"],
     "html": [r"ghost\.io", r"/assets/built/"]},
    {"nombre": "Wix", "categoria": "CMS",
     "meta_generador": [r"wix\.com"],
     "html": [r"static\.wixstatic\.com", r"X-Wix-"],
     "cabeceras_cualquiera": [r"x-wix-"]},
    {"nombre": "Squarespace", "categoria": "CMS",
     "html": [r"static1?\.squarespace\.com", r"squarespace\.com/universal/scripts-compressed"],
     "cabeceras": [("server", r"squarespace")]},
    {"nombre": "Webflow", "categoria": "CMS",
     "meta_generador": [r"webflow"],
     "html": [r"assets\.website-files\.com", r"data-wf-page"]},
    {"nombre": "Blogger", "categoria": "CMS",
     "meta_generador": [r"blogger"]},
    {"nombre": "PrestaShop", "categoria": "CMS",
     "meta_generador": [r"prestashop"],
     "cookies": [r"^PrestaShop-"],
     "html": [r"prestashop"]},
    {"nombre": "Craft CMS", "categoria": "CMS",
     "cookies": [r"^CraftSessionId"],
     "cabeceras": [("x-powered-by", r"craft cms")]},
    {"nombre": "TYPO3", "categoria": "CMS",
     "meta_generador": [r"typo3"]},
    {"nombre": "Sitecore", "categoria": "CMS",
     "html": [r"/sitecore/", r"sc_itemid"],
     "cookies": [r"SC_ANALYTICS_GLOBAL_COOKIE"]},
    {"nombre": "Contentful", "categoria": "CMS",
     "html": [r"ctfassets\.net", r"contentful"]},
    {"nombre": "Duda", "categoria": "CMS",
     "html": [r"dudaone\.com", r"dudamobile\.com", r"cdn\.dudaone"]},
    {"nombre": "Weebly", "categoria": "CMS",
     "html": [r"weebly\.com", r"weebly-main"]},
    {"nombre": "Odoo", "categoria": "CMS",
     "html": [r"data-oe-model", r"odoo\.com"]},
    {"nombre": "HubSpot CMS", "categoria": "CMS",
     "html": [r"hs-inline-css", r"hubspotusercontent"]},

    # ------------------------------------------------------------- Ecommerce
    {"nombre": "Shopify", "categoria": "Ecommerce",
     "html": [r"cdn\.shopify\.com", r"myshopify\.com", r"Shopify\.theme"],
     "cookies": [r"_shopify_", r"_secure_session_id"],
     "cabeceras": [("server", r"shopify")]},
    {"nombre": "WooCommerce", "categoria": "Ecommerce",
     "html": [r"woocommerce", r"wc-cart-fragments", r"add-to-cart"]},
    {"nombre": "Magento / Adobe Commerce", "categoria": "Ecommerce",
     "html": [r"/static/version\d+/frontend/", r"Mage\.Cookies", r"mage/cookies"],
     "cookies": [r"^mage-", r"^frontend$"],
     "cabeceras": [("x-magento-cache-debug", r"."), ("x-magento-tags", r".")]},
    {"nombre": "BigCommerce", "categoria": "Ecommerce",
     "html": [r"cdn\d+\.bigcommerce\.com", r"bigcommerce\.com/s/"]},
    {"nombre": "VTEX", "categoria": "Ecommerce",
     "html": [r"vtexcommercestable", r"vtexassets\.com", r"\.vteximg\.com\.br"]},
    {"nombre": "TiendaNube / Nuvemshop", "categoria": "Ecommerce",
     "html": [r"tiendanube", r"nuvemshop"]},
    {"nombre": "Mercado Shops", "categoria": "Ecommerce",
     "html": [r"mercadoshops\.com"]},
    {"nombre": "Ecwid", "categoria": "Ecommerce",
     "html": [r"app\.ecwid\.com", r"ecwid\.com/script"]},
    {"nombre": "OpenCart", "categoria": "Ecommerce",
     "html": [r"index\.php\?route=", r"catalog/view/theme/"],
     "cookies": [r"^OCSESSID"]},
    {"nombre": "Salesforce Commerce Cloud", "categoria": "Ecommerce",
     "html": [r"demandware", r"salesforce-commerce"]},
    {"nombre": "Square Online", "categoria": "Ecommerce",
     "html": [r"squareonline", r"square\.site"]},

    # ------------------------------------------------------------- Analytics
    {"nombre": "Google Analytics 4", "categoria": "Analytics",
     "html": [r"googletagmanager\.com/gtag/js\?id=G-", r"gtag\(['\"]config['\"],\s*['\"]G-"]},
    {"nombre": "Universal Analytics (GA3)", "categoria": "Analytics",
     "html": [r"google-analytics\.com/analytics\.js", r"UA-\d{4,}-\d+"]},
    {"nombre": "Google Tag Manager", "categoria": "Analytics",
     "html": [r"googletagmanager\.com/gtm\.js", r"GTM-[A-Z0-9]{4,}"]},
    {"nombre": "Hotjar", "categoria": "Analytics",
     "html": [r"static\.hotjar\.com", r"hotjar\.com/c/hotjar"]},
    {"nombre": "Microsoft Clarity", "categoria": "Analytics",
     "html": [r"clarity\.ms"]},
    {"nombre": "Matomo", "categoria": "Analytics",
     "html": [r"matomo\.js", r"piwik\.js", r"matomo\.php"]},
    {"nombre": "Mixpanel", "categoria": "Analytics",
     "html": [r"cdn\.mxpnl\.com", r"mixpanel\.com/libs"]},
    {"nombre": "Amplitude", "categoria": "Analytics",
     "html": [r"cdn\.amplitude\.com", r"amplitude\.com/libs"]},
    {"nombre": "Segment", "categoria": "Analytics",
     "html": [r"cdn\.segment\.com", r"segment\.io"]},
    {"nombre": "Heap", "categoria": "Analytics",
     "html": [r"cdn\.heapanalytics\.com", r"heap-\d+\.js"]},
    {"nombre": "Plausible", "categoria": "Analytics",
     "html": [r"plausible\.io/js"]},
    {"nombre": "Adobe Analytics", "categoria": "Analytics",
     "html": [r"omtrdc\.net", r"AppMeasurement\.js", r"2o7\.net"]},
    {"nombre": "Crazy Egg", "categoria": "Analytics",
     "html": [r"script\.crazyegg\.com"]},
    {"nombre": "PostHog", "categoria": "Analytics",
     "html": [r"posthog\.com", r"app\.posthog\.com"]},

    # ----------------------------------------------------------- Advertising
    {"nombre": "Meta Pixel (Facebook)", "categoria": "Advertising",
     "html": [r"connect\.facebook\.net/[a-z_]+/fbevents\.js", r"fbq\("]},
    {"nombre": "Google Ads", "categoria": "Advertising",
     "html": [r"googleadservices\.com", r"google_conversion", r"AW-\d{6,}"]},
    {"nombre": "Google AdSense", "categoria": "Advertising",
     "html": [r"pagead2?\.googlesyndication\.com", r"adsbygoogle"]},
    {"nombre": "DoubleClick", "categoria": "Advertising",
     "html": [r"doubleclick\.net"]},
    {"nombre": "LinkedIn Insight Tag", "categoria": "Advertising",
     "html": [r"snap\.licdn\.com"]},
    {"nombre": "TikTok Pixel", "categoria": "Advertising",
     "html": [r"analytics\.tiktok\.com", r"ttq\."]},
    {"nombre": "Pinterest Tag", "categoria": "Advertising",
     "html": [r"ct\.pinterest\.com", r"pintrk\("]},
    {"nombre": "X (Twitter) Pixel", "categoria": "Advertising",
     "html": [r"static\.ads-twitter\.com", r"analytics\.twitter\.com"]},
    {"nombre": "Criteo", "categoria": "Advertising",
     "html": [r"criteo\.(com|net)"]},
    {"nombre": "Microsoft Advertising (UET)", "categoria": "Advertising",
     "html": [r"bat\.bing\.com"]},
    {"nombre": "Snapchat Pixel", "categoria": "Advertising",
     "html": [r"sc-static\.net/scevent"]},
    {"nombre": "Taboola", "categoria": "Advertising",
     "html": [r"cdn\.taboola\.com"]},
    {"nombre": "Outbrain", "categoria": "Advertising",
     "html": [r"widgets\.outbrain\.com"]},
    {"nombre": "AdRoll", "categoria": "Advertising",
     "html": [r"s\.adroll\.com"]},
    {"nombre": "Amazon Advertising", "categoria": "Advertising",
     "html": [r"amazon-adsystem\.com"]},

    # -------------------------------------------------------------- Payments
    {"nombre": "Stripe", "categoria": "Payments",
     "html": [r"js\.stripe\.com", r"m\.stripe\.network", r"stripe\.com/v3"]},
    {"nombre": "PayPal", "categoria": "Payments",
     "html": [r"paypal\.com/sdk", r"paypalobjects\.com", r"paypal\.com/webapps"]},
    {"nombre": "Mercado Pago", "categoria": "Payments",
     "html": [r"sdk\.mercadopago\.com", r"mercadopago\.com", r"mlstatic\.com"]},
    {"nombre": "Conekta", "categoria": "Payments",
     "html": [r"conekta\.io", r"conekta\.js"]},
    {"nombre": "Openpay", "categoria": "Payments",
     "html": [r"js\.openpay\.mx", r"openpay\.mx"]},
    {"nombre": "Adyen", "categoria": "Payments",
     "html": [r"checkoutshopper[^\"']*\.adyen\.com", r"adyen\.com/hpp"]},
    {"nombre": "Braintree", "categoria": "Payments",
     "html": [r"js\.braintreegateway\.com", r"braintree-api\.com"]},
    {"nombre": "Square", "categoria": "Payments",
     "html": [r"squarecdn\.com", r"js\.squareup\.com", r"squareup\.com/payments"]},
    {"nombre": "Razorpay", "categoria": "Payments",
     "html": [r"checkout\.razorpay\.com"]},
    {"nombre": "Kushki", "categoria": "Payments",
     "html": [r"kushkipagos\.com", r"cdn\.kushki"]},
    {"nombre": "PayU", "categoria": "Payments",
     "html": [r"payu\.com", r"secure\.payu"]},
    {"nombre": "Authorize.Net", "categoria": "Payments",
     "html": [r"authorize\.net", r"js\.authorize\.net"]},
    {"nombre": "Klarna", "categoria": "Payments",
     "html": [r"klarna\.com/web-sdk", r"x\.klarnacdn\.net"]},
    {"nombre": "Affirm", "categoria": "Payments",
     "html": [r"cdn1?\.affirm\.com"]},
    {"nombre": "Checkout.com", "categoria": "Payments",
     "html": [r"cdn\.checkout\.com"]},
    {"nombre": "2Checkout (Verifone)", "categoria": "Payments",
     "html": [r"2checkout\.com", r"2co\.com"]},
    {"nombre": "Worldpay", "categoria": "Payments",
     "html": [r"worldpay\.com", r"cdn\.worldpay"]},

    # -------------------------------------------------------- Chat y soporte
    {"nombre": "Intercom", "categoria": "Chat y soporte",
     "html": [r"widget\.intercom\.io", r"intercomcdn\.com"]},
    {"nombre": "Zendesk", "categoria": "Chat y soporte",
     "html": [r"static\.zdassets\.com", r"zendesk\.com/embeddable", r"v2\.zopim\.com"]},
    {"nombre": "Tawk.to", "categoria": "Chat y soporte",
     "html": [r"embed\.tawk\.to"]},
    {"nombre": "Drift", "categoria": "Chat y soporte",
     "html": [r"js\.driftt\.com", r"js\.drift\.com"]},
    {"nombre": "LiveChat", "categoria": "Chat y soporte",
     "html": [r"cdn\.livechatinc\.com", r"secure\.livechatinc\.com"]},
    {"nombre": "Crisp", "categoria": "Chat y soporte",
     "html": [r"client\.crisp\.chat"]},
    {"nombre": "HubSpot Chat", "categoria": "Chat y soporte",
     "html": [r"js\.usemessages\.com"]},
    {"nombre": "Freshdesk / Freshchat", "categoria": "Chat y soporte",
     "html": [r"wchat\.freshchat\.com", r"freshdesk\.com"]},
    {"nombre": "Tidio", "categoria": "Chat y soporte",
     "html": [r"code\.tidio\.co"]},
    {"nombre": "Olark", "categoria": "Chat y soporte",
     "html": [r"static\.olark\.com"]},
    {"nombre": "WhatsApp (widget/enlace)", "categoria": "Chat y soporte",
     "html": [r"wa\.me/", r"api\.whatsapp\.com/send", r"chat\.whatsapp\.com"]},
    {"nombre": "Help Scout", "categoria": "Chat y soporte",
     "html": [r"beacon-v2\.helpscout\.net"]},
    {"nombre": "Tidio Chat", "categoria": "Chat y soporte",
     "html": [r"tidiochat"]},
    {"nombre": "Smartsupp", "categoria": "Chat y soporte",
     "html": [r"smartsupp(chat)?\.com"]},
    {"nombre": "Chatwoot", "categoria": "Chat y soporte",
     "html": [r"chatwoot"]},

    # -------------------------------------------------------------- Marketing
    {"nombre": "HubSpot", "categoria": "Marketing",
     "html": [r"js\.hs-scripts\.com", r"js\.hs-analytics\.net", r"hsforms\.net"]},
    {"nombre": "Mailchimp", "categoria": "Marketing",
     "html": [r"chimpstatic\.com", r"list-manage\.com", r"s3\.amazonaws\.com/downloads\.mailchimp"]},
    {"nombre": "Klaviyo", "categoria": "Marketing",
     "html": [r"static\.klaviyo\.com", r"klaviyo\.com/onsite"]},
    {"nombre": "Brevo (Sendinblue)", "categoria": "Marketing",
     "html": [r"sibautomation\.com", r"sendinblue", r"brevo\.com"]},
    {"nombre": "ActiveCampaign", "categoria": "Marketing",
     "html": [r"activehosted\.com", r"trackcmp\.net"]},
    {"nombre": "Salesforce Marketing Cloud / Pardot", "categoria": "Marketing",
     "html": [r"pi\.pardot\.com", r"pardot\.com"]},
    {"nombre": "Marketo", "categoria": "Marketing",
     "html": [r"munchkin\.marketo\.net", r"marketo\.net"]},
    {"nombre": "RD Station", "categoria": "Marketing",
     "html": [r"rdstation\.com", r"d335luupugsy2\.cloudfront\.net"]},
    {"nombre": "Drip", "categoria": "Marketing",
     "html": [r"tag\.getdrip\.com"]},
    {"nombre": "ConvertKit", "categoria": "Marketing",
     "html": [r"convertkit\.com", r"ck\.page"]},
    {"nombre": "Omnisend", "categoria": "Marketing",
     "html": [r"omnisend\.com", r"omnisnippet"]},
    {"nombre": "OneSignal (push)", "categoria": "Marketing",
     "html": [r"onesignal\.com"]},

    # ---------------------------------------------------------------- Reviews
    {"nombre": "Trustpilot", "categoria": "Reviews",
     "html": [r"widget\.trustpilot\.com", r"trustpilot\.com"]},
    {"nombre": "Yotpo", "categoria": "Reviews",
     "html": [r"staticw2\.yotpo\.com", r"yotpo\.com"]},
    {"nombre": "Judge.me", "categoria": "Reviews",
     "html": [r"judge\.me", r"cdn\.judge\.me"]},
    {"nombre": "Okendo", "categoria": "Reviews",
     "html": [r"d3hw6dc1ow8pp2\.cloudfront\.net", r"okendo\.io"]},
    {"nombre": "Stamped.io", "categoria": "Reviews",
     "html": [r"cdn-stamped-io", r"stamped\.io"]},
    {"nombre": "Bazaarvoice", "categoria": "Reviews",
     "html": [r"bazaarvoice\.com"]},
    {"nombre": "Reviews.io", "categoria": "Reviews",
     "html": [r"widget\.reviews\.io", r"reviews\.io"]},
    {"nombre": "Loox", "categoria": "Reviews",
     "html": [r"loox\.io", r"loox"]},
    {"nombre": "Google Customer Reviews", "categoria": "Reviews",
     "html": [r"www\.google\.com/shopping/customerreviews"]},

    # ---------------------------------------------------------------- Consent
    {"nombre": "OneTrust", "categoria": "Consent",
     "html": [r"cdn\.cookielaw\.org", r"onetrust"]},
    {"nombre": "Cookiebot", "categoria": "Consent",
     "html": [r"consent\.cookiebot\.(com|eu)"]},
    {"nombre": "TrustArc", "categoria": "Consent",
     "html": [r"consent\.trustarc\.com", r"consent\.truste\.com"]},
    {"nombre": "Quantcast Choice", "categoria": "Consent",
     "html": [r"quantcast\.mgr\.consensu\.org", r"choice\.quantcast\.com"]},
    {"nombre": "Iubenda", "categoria": "Consent",
     "html": [r"cdn\.iubenda\.com", r"iubenda\.com"]},
    {"nombre": "CookieYes", "categoria": "Consent",
     "html": [r"cookieyes", r"cdn-cookieyes"]},
    {"nombre": "Didomi", "categoria": "Consent",
     "html": [r"sdk\.privacy-center\.org", r"didomi"]},
    {"nombre": "Osano", "categoria": "Consent",
     "html": [r"consent\.osano\.com", r"osano\.com"]},
    {"nombre": "Axeptio", "categoria": "Consent",
     "html": [r"static\.axept\.io", r"axeptio"]},
    {"nombre": "Complianz (WordPress)", "categoria": "Consent",
     "html": [r"complianz"]},
    {"nombre": "Cookie Information", "categoria": "Consent",
     "html": [r"policy\.cookieinformation\.com"]},
    {"nombre": "Termly", "categoria": "Consent",
     "html": [r"app\.termly\.io", r"termly\.io"]},
    {"nombre": "Usercentrics", "categoria": "Consent",
     "html": [r"usercentrics\.eu", r"usercentrics\.com"]},

    # --------------------------------------------------------- Experimentation
    {"nombre": "Optimizely", "categoria": "Experimentation",
     "html": [r"cdn\.optimizely\.com", r"logx\.optimizely\.com"]},
    {"nombre": "VWO", "categoria": "Experimentation",
     "html": [r"dev\.visualwebsiteoptimizer\.com", r"vwo\.com"]},
    {"nombre": "Google Optimize", "categoria": "Experimentation",
     "html": [r"www\.googleoptimize\.com", r"optimize\.google\.com"]},
    {"nombre": "AB Tasty", "categoria": "Experimentation",
     "html": [r"try\.abtasty\.com", r"abtasty\.com"]},
    {"nombre": "Convert", "categoria": "Experimentation",
     "html": [r"cdn-3\.convertexperiments\.com", r"convertexperiments"]},
    {"nombre": "Dynamic Yield", "categoria": "Experimentation",
     "html": [r"cdn\.dynamicyield\.com"]},
    {"nombre": "Kameleoon", "categoria": "Experimentation",
     "html": [r"kameleoon\.eu", r"kameleoon"]},

    # ------------------------------------------------------------------ Search
    {"nombre": "Algolia", "categoria": "Search",
     "html": [r"algolia\.net", r"algolianet\.com", r"algoliasearch"]},
    {"nombre": "Swiftype (Elastic)", "categoria": "Search",
     "html": [r"swiftype\.com", r"install\.swiftype"]},
    {"nombre": "Doofinder", "categoria": "Search",
     "html": [r"doofinder\.com", r"df_lvp"]},
    {"nombre": "Coveo", "categoria": "Search",
     "html": [r"coveo\.com", r"platform\.cloud\.coveo"]},
    {"nombre": "Searchspring", "categoria": "Search",
     "html": [r"searchspring\.net"]},
    {"nombre": "Klevu", "categoria": "Search",
     "html": [r"klevu\.com", r"stats\.klevu"]},

    # -------------------------------------------------------------- Scheduling
    {"nombre": "Calendly", "categoria": "Scheduling",
     "html": [r"assets\.calendly\.com", r"calendly\.com/"]},
    {"nombre": "Acuity Scheduling (Squarespace)", "categoria": "Scheduling",
     "html": [r"acuityscheduling\.com"]},
    {"nombre": "Square Appointments", "categoria": "Scheduling",
     "html": [r"squareup\.com/appointments", r"appointments\.squareup"]},
    {"nombre": "SimplyBook.me", "categoria": "Scheduling",
     "html": [r"simplybook\.(me|it)"]},
    {"nombre": "Setmore", "categoria": "Scheduling",
     "html": [r"setmore\.com", r"my\.setmore"]},
    {"nombre": "HubSpot Meetings", "categoria": "Scheduling",
     "html": [r"meetings\.hubspot\.com", r"static\.hubspot\.com.*meetings"]},
    {"nombre": "YouCanBook.me", "categoria": "Scheduling",
     "html": [r"youcanbook\.me"]},
    {"nombre": "Cal.com", "categoria": "Scheduling",
     "html": [r"cal\.com/embed"]},

    # -------------------------------------------------------------- Frameworks
    {"nombre": "React", "categoria": "Frameworks",
     "html": [r"react(\.production)?\.min\.js", r"data-reactroot", r"react-dom"]},
    {"nombre": "Next.js", "categoria": "Frameworks",
     "html": [r"/_next/", r"__NEXT_DATA__"],
     "cabeceras": [("x-powered-by", r"next\.js")]},
    {"nombre": "Vue.js", "categoria": "Frameworks",
     "html": [r"vue(\.min|\.global)?\.js", r"vue@", r"data-v-app"]},
    {"nombre": "Nuxt", "categoria": "Frameworks",
     "html": [r"/_nuxt/", r"__NUXT__"],
     "meta_generador": [r"nuxt"]},
    {"nombre": "Angular (2+)", "categoria": "Frameworks",
     "html": [r"ng-version=", r"ng-app=\""]},
    {"nombre": "AngularJS (1.x)", "categoria": "Frameworks",
     "html": [r"angular(\.min)?\.js"]},
    {"nombre": "jQuery", "categoria": "Frameworks",
     "html": [r"jquery[-.]?\d", r"jquery\.min\.js", r"jquery-migrate"]},
    {"nombre": "Bootstrap", "categoria": "Frameworks",
     "html": [r"bootstrap(\.min)?\.(css|js)", r"cdn\.jsdelivr[^\"']*bootstrap"]},
    {"nombre": "Tailwind CSS", "categoria": "Frameworks",
     "html": [r"cdn\.tailwindcss\.com", r"tailwind(?:css|\.config)"]},
    {"nombre": "Gatsby", "categoria": "Frameworks",
     "html": [r"___gatsby", r"gatsby-browser"]},
    {"nombre": "Astro", "categoria": "Frameworks",
     "meta_generador": [r"astro"]},
    {"nombre": "Remix", "categoria": "Frameworks",
     "html": [r"__remixContext", r"remix\.run"]},
    {"nombre": "Alpine.js", "categoria": "Frameworks",
     "html": [r"alpinejs", r"x-on:click="]},
    {"nombre": "HTMX", "categoria": "Frameworks",
     "html": [r"htmx(\.min)?\.js", r"hx-get="]},
    {"nombre": "Livewire", "categoria": "Frameworks",
     "html": [r"livewire"]},
    {"nombre": "Emotion (CSS-in-JS)", "categoria": "Frameworks",
     "html": [r"css-[a-z0-9]{6}-e", r"@emotion"]},

    # ---------------------------------------------------------- CDN y hosting
    {"nombre": "Cloudflare", "categoria": "CDN y hosting",
     "cabeceras": [("server", r"^cloudflare"), ("cf-ray", r"."), ("cf-cache-status", r".")],
     "cookies": [r"^__cf_", r"^cf_clearance"]},
    {"nombre": "Akamai", "categoria": "CDN y hosting",
     "cabeceras": [("server", r"AkamaiGHost")],
     "cabeceras_cualquiera": [r"akamai-?origin|x-akamai|akamaighost"]},
    {"nombre": "Fastly", "categoria": "CDN y hosting",
     "cabeceras_cualquiera": [r"fastly", r"x-served-by: cache-"]},
    {"nombre": "Amazon CloudFront", "categoria": "CDN y hosting",
     "cabeceras": [("x-amz-cf-id", r"."), ("x-amz-cf-pop", r".")],
     "cabeceras_cualquiera": [r"cloudfront"]},
    {"nombre": "Amazon S3", "categoria": "CDN y hosting",
     "cabeceras": [("server", r"amazons3")]},
    {"nombre": "Vercel", "categoria": "CDN y hosting",
     "cabeceras": [("x-vercel-id", r"."), ("server", r"vercel")],
     "cabeceras_cualquiera": [r"x-vercel"]},
    {"nombre": "Netlify", "categoria": "CDN y hosting",
     "cabeceras": [("x-nf-request-id", r"."), ("server", r"netlify")]},
    {"nombre": "Google Cloud / App Engine", "categoria": "CDN y hosting",
     "cabeceras": [("server", r"google frontend|^gws$")]},
    {"nombre": "Microsoft Azure", "categoria": "CDN y hosting",
     "cabeceras_cualquiera": [r"x-ms-", r"x-azure-ref"]},
    {"nombre": "Bunny CDN", "categoria": "CDN y hosting",
     "cabeceras_cualquiera": [r"bunnycdn", r"cdn-pullzone"]},
    {"nombre": "Sucuri", "categoria": "CDN y hosting",
     "cabeceras_cualquiera": [r"x-sucuri"]},
    {"nombre": "Imperva Incapsula", "categoria": "CDN y hosting",
     "cookies": [r"^incap_ses", r"^visid_incap"],
     "cabeceras": [("x-iinfo", r".")]},
    {"nombre": "KeyCDN", "categoria": "CDN y hosting",
     "cabeceras": [("server", r"keycdn")]},
    {"nombre": "WP Engine", "categoria": "CDN y hosting",
     "cabeceras_cualquiera": [r"x-wpe-"]},
    {"nombre": "Pantheon", "categoria": "CDN y hosting",
     "cabeceras_cualquiera": [r"x-pantheon"]},
    {"nombre": "Heroku", "categoria": "CDN y hosting",
     "cabeceras": [("via", r"vegur")]},
    {"nombre": "GitHub Pages", "categoria": "CDN y hosting",
     "cabeceras": [("server", r"github\.com")]},
    {"nombre": "Shopify (hosting)", "categoria": "CDN y hosting",
     "cabeceras": [("server", r"shopify")],
     "html": [r"cdn\.shopify\.com"]},

    # ------------------------------------------------------------------ Server
    {"nombre": "nginx", "categoria": "Server",
     "cabeceras": [("server", r"^nginx")]},
    {"nombre": "Apache", "categoria": "Server",
     "cabeceras": [("server", r"^apache")]},
    {"nombre": "Microsoft IIS", "categoria": "Server",
     "cabeceras": [("server", r"microsoft-iis")]},
    {"nombre": "LiteSpeed", "categoria": "Server",
     "cabeceras": [("server", r"litespeed")]},
    {"nombre": "Caddy", "categoria": "Server",
     "cabeceras": [("server", r"^caddy")]},
    {"nombre": "OpenResty", "categoria": "Server",
     "cabeceras": [("server", r"openresty")]},
    {"nombre": "PHP", "categoria": "Server",
     "cabeceras": [("x-powered-by", r"php")],
     "cookies": [r"^PHPSESSID"]},
    {"nombre": "ASP.NET", "categoria": "Server",
     "cabeceras": [("x-powered-by", r"asp\.net"), ("x-aspnet-version", r".")]},
    {"nombre": "Express (Node.js)", "categoria": "Server",
     "cabeceras": [("x-powered-by", r"express")]},
    {"nombre": "Next.js (runtime)", "categoria": "Server",
     "cabeceras": [("x-powered-by", r"next\.js")]},
    {"nombre": "Django", "categoria": "Server",
     "cookies": [r"^csrftoken$", r"^django_language"]},
    {"nombre": "Laravel", "categoria": "Server",
     "cookies": [r"^laravel_session", r"^XSRF-TOKEN"],
     "html": [r"Laravel"]},
    {"nombre": "Tomcat / Apache Coyote", "categoria": "Server",
     "cabeceras": [("server", r"apache-coyote|tomcat")]},
    {"nombre": "Ruby on Rails", "categoria": "Server",
     "cabeceras": [("server", r"phusion passenger"), ("x-runtime", r".")]},

    # ------------------------------------------------- Seguridad y monitoreo
    {"nombre": "Google reCAPTCHA", "categoria": "Seguridad y monitoreo",
     "html": [r"google\.com/recaptcha", r"grecaptcha"]},
    {"nombre": "hCaptcha", "categoria": "Seguridad y monitoreo",
     "html": [r"hcaptcha\.com"]},
    {"nombre": "Cloudflare Turnstile", "categoria": "Seguridad y monitoreo",
     "html": [r"challenges\.cloudflare\.com/turnstile"]},
    {"nombre": "Sentry", "categoria": "Seguridad y monitoreo",
     "html": [r"browser\.sentry-cdn\.com", r"@sentry/", r"Sentry\.init"]},
    {"nombre": "New Relic", "categoria": "Seguridad y monitoreo",
     "html": [r"newrelic", r"bam\.nr-data\.net"]},
    {"nombre": "Datadog RUM", "categoria": "Seguridad y monitoreo",
     "html": [r"datadoghq\.com", r"dd-rum"]},
    {"nombre": "Bugsnag", "categoria": "Seguridad y monitoreo",
     "html": [r"bugsnag", r"d2wy8f7a9ursnm\.cloudfront\.net"]},
    {"nombre": "LogRocket", "categoria": "Seguridad y monitoreo",
     "html": [r"logrocket", r"cdn\.logr-ingest"]},
    {"nombre": "FullStory", "categoria": "Seguridad y monitoreo",
     "html": [r"fullstory\.com", r"fs\.js"]},
    {"nombre": "Mouseflow", "categoria": "Seguridad y monitoreo",
     "html": [r"mouseflow\.com"]},
    {"nombre": "HUMAN / PerimeterX", "categoria": "Seguridad y monitoreo",
     "html": [r"px-cloud", r"perimeterx", r"px-captcha"],
     "cookies": [r"^_px"]},
    {"nombre": "Imperva (WAF)", "categoria": "Seguridad y monitoreo",
     "cookies": [r"^incap_ses", r"^visid_incap"],
     "cabeceras": [("x-iinfo", r".")]},
    {"nombre": "reCAPTCHA Enterprise", "categoria": "Seguridad y monitoreo",
     "html": [r"recaptcha/enterprise"]},

    # ------------------------------------------------------------ Media y mapas
    {"nombre": "Google Maps", "categoria": "Media y mapas",
     "html": [r"maps\.googleapis\.com", r"maps\.google\.com/maps", r"@googlemaps/"]},
    {"nombre": "Mapbox", "categoria": "Media y mapas",
     "html": [r"api\.mapbox\.com", r"mapbox-gl"]},
    {"nombre": "Leaflet / OpenStreetMap", "categoria": "Media y mapas",
     "html": [r"leaflet(\.js|@[0-9])", r"openstreetmap\.org"]},
    {"nombre": "HERE Maps", "categoria": "Media y mapas",
     "html": [r"js\.api\.here\.com"]},
    {"nombre": "YouTube (embed)", "categoria": "Media y mapas",
     "html": [r"youtube\.com/embed", r"youtube-nocookie\.com"]},
    {"nombre": "Vimeo (embed)", "categoria": "Media y mapas",
     "html": [r"player\.vimeo\.com"]},
    {"nombre": "Wistia", "categoria": "Media y mapas",
     "html": [r"wistia\.com", r"fast\.wistia"]},
    {"nombre": "Cloudinary", "categoria": "Media y mapas",
     "html": [r"res\.cloudinary\.com", r"cloudinary\.com"]},
    {"nombre": "Imgix", "categoria": "Media y mapas",
     "html": [r"imgix\.net"]},
    {"nombre": "Dailymotion", "categoria": "Media y mapas",
     "html": [r"dailymotion\.com/embed"]},
    {"nombre": "Twitch (embed)", "categoria": "Media y mapas",
     "html": [r"player\.twitch\.tv"]},
    {"nombre": "Google Fonts", "categoria": "Media y mapas",
     "html": [r"fonts\.googleapis\.com", r"fonts\.gstatic\.com"]},
    {"nombre": "Font Awesome", "categoria": "Media y mapas",
     "html": [r"font-?awesome", r"use\.fontawesome\.com"]},
]
